name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types:
      - published

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      # Step to fix npm vulnerabilities
      - name: Fix npm vulnerabilities
        run: |
          npm ci
          npm audit --production
          npm audit fix --force

      # Additional steps such as linting and documentation generation
      - name: Run linting
        run: npm run lint

      - name: Generate docs
        run: npm run docs

      # Test step
      - name: Test ${{ matrix.os }}
        run: |
          npm ci
          npm run test

      # Code coverage step (conditionally run on Linux)
      - name: Code coverage
        if: contains(runner.os, 'Linux')
        run: codecov/codecov-action@v1
          with:
            file: coverage/lcov.info
            verbose: true

      # Build step
      - name: Build ${{ matrix.os }}
        run: |
          npm ci
          npm run build
          if [ "${{ runner.os }}" == "Linux" ]; then
            node ./build.js -o linux -p deb -a x64
            node ./build.js -o linux -p AppImage -a x64
          elif [ "${{ runner.os }}" == "macOS" ]; then
            node ./build.js -o darwin -p dmg -a x64
          elif [ "${{ runner.os }}" == "Windows" ]; then
            node ./build.js -o win32 -p portable -a x64
          fi

      # Artifact archiving step
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ubports-installer
          path: |
            dist/*.deb
            dist/*.AppImage
            dist/*.dmg
            dist/*.exe

      # Release asset upload step (conditionally run on release)
      - name: Upload release assets
        if: github.event_name == 'release'
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const { repo: { owner, repo }} = context;
            const tag = context.ref.replace("refs/tags/", "");
            console.log("trying to upload to", owner, repo, tag);
            const crypto = require('crypto');
            const sha256sum = path => new Promise((resolve, reject) => {
              const hash = crypto.createHash('sha256');
              const stream = fs.createReadStream(path);
              stream.on('error', reject);
              stream.on('data', chunk => hash.update(chunk));
              stream.on('end', () => resolve(hash.digest('hex')));
            });
            github.repos.getReleaseByTag({ owner, repo, tag })
              .then(({data: {id: release_id}}) =>
                Promise.all(
                  fs.readdirSync('./dist/').filter(f =>
                      f.match(/ubports-installer_*.*/) &&
                      !f.includes("snap") &&
                      !f.includes("blockmap")
                    )
                    .map(file =>
                      github.repos.uploadReleaseAsset({
                        owner, repo, release_id,
                        name: file,
                        data: fs.readFileSync(`./dist/${file}`)
                      })
                      .then(() => console.log("uploaded", file))
                      .then(() => sha256sum(`./dist/${file}`))
                      .then(data =>
                        github.repos.uploadReleaseAsset({
                          owner, repo, release_id, data,
                          name: `${file}.sha256`
                        })
                      )
                      .then(() => console.log("uploaded checksum for", file))
                  )
                )
              )
